/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_sdk_jni_kestrel_KestrelStructHh */

#ifndef _Included_com_sdk_jni_kestrel_KestrelStructHh
#define _Included_com_sdk_jni_kestrel_KestrelStructHh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sdk_jni_kestrel_KestrelStructHh
 * Method:    kestrel_env_init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sdk_jni_kestrel_KestrelStructHh_kestrel_1env_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_sdk_jni_kestrel_KestrelStructHh
 * Method:    kestrel_env_deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sdk_jni_kestrel_KestrelStructHh_kestrel_1env_1deinit
  (JNIEnv *, jobject);

/*
 * Class:     com_sdk_jni_kestrel_KestrelStructHh
 * Method:    kestrel_license_add_from_file
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_com_sdk_jni_kestrel_KestrelStructHh_kestrel_1license_1add_1from_1file
  (JNIEnv *env, jobject);

/*
 * Class:     com_sdk_jni_kestrel_KestrelStructHh
 * Method:    kestrel_plugin_load
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_com_sdk_jni_kestrel_KestrelStructHh_kestrel_1plugin_1load
  (JNIEnv *env, jobject);

/*
 * Class:     com_sdk_jni_kestrel_KestrelStructHh
 * Method:    kestrel_annotator_open
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_com_sdk_jni_kestrel_KestrelStructHh_kestrel_1annotator_1open
  (JNIEnv *env, jobject);

/*
 * Class:     com_sdk_jni_kestrel_KestrelStructHh
 * Method:    kestrel_annotator_process
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sdk_jni_kestrel_KestrelStructHh_kestrel_1annotator_1process
  (JNIEnv *env, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
